### ISSUE TITLE
Electron audio sync and output selection

### ISSUE THREAD

**Issue by fftreynolds** [steveseguin/electroncapture#44]
Testing using Electron capture as a permanent software decoder. 
Currently running win 10 x64 v1909
Electron version 1.1.3

When running electron the audio selection drop down box is not working. Audio is always sending on the windows default audio output. Audio is about 1 or slightly more than 1 second behind video.

**Comment by steveseguin** [comment]
Just to confirm for later, but you said you select the audio device in the drop down box, but it doesn't actually playout to that audio device.

Are you using OBS.Ninja or are you using your own private deployment of OBS.Ninja?

**Comment by fftreynolds** [comment]
Oh good through. I am running my own deployment. I updated to 13.4 yesterday. Tested using obs.ninja directly and both bugs are not present. Lipsync looks good and audio selector works properly.

**Comment by steveseguin** [comment]
You can go to YOURDOMAIN.com/electron in the electron app , and get the &sink=xxxid value there.  You can use that going forward and it will work on the default page then too.

You can also use &outputdevice=LABELNAME , instead of using the &sink parameter -- that is an alternative to &sink and it will work across domains.

The reason for this all is that the audio device's ID is specific to the domain--- this is a privacy feature of Chrome. It's super annoying.  I might update the Electron app to not use the sink ID, but rather the label name instead -- it's just not very exact and will fail with some odd labels.

**Comment by fftreynolds** [comment]
seems like you have the exact issue here. Going to close the bug. 

thanks a bunch
